<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1412949538852" stop="1412949560076" version="1.4.4-SNAPSHOT">
    <name>my.company.SimpleTest</name>
    <test-cases>
        <test-case start="1412949558829" stop="1412949558830" status="failed">
            <name>failedSimpleTest</name>
            <failure>
                <message>AssertionError: 5 is not 2 + 2
Expected: is &lt;4&gt;
     but: was &lt;5&gt;</message>
                <stack-trace>java.lang.AssertionError: 5 is not 2 + 2
Expected: is &lt;4&gt;
     but: was &lt;5&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at my.company.SimpleTest.failedSimpleTest(SimpleTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-27"/>
            </labels>
        </test-case>
        <test-case start="1412949558829" stop="1412949558829" status="passed">
            <name>longTitleTest</name>
            <title>Test what do nothing and always passed right, but have a very long title, over 100 symbols, seriously</title>
            <description type="text">I hate descriptions! See the title!</description>
            <steps/>
            <attachments/>
            <labels>
                <label name="story" value="SuccessStory"/>
                <label name="feature" value="SimpleStories"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-9"/>
            </labels>
        </test-case>
        <test-case start="1412949558829" stop="1412949558832" status="broken">
            <name>brokenSimpleTest</name>
            <failure>
                <message>ArrayIndexOutOfBoundsException: 1</message>
                <stack-trace>java.lang.ArrayIndexOutOfBoundsException: 1
	at my.company.SimpleTest.brokenSimpleTest(SimpleTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-25"/>
            </labels>
        </test-case>
        <test-case start="1412949558831" stop="1412949558832" status="pending">
            <name>my.company.SimpleTest</name>
            <title>skippedSimpleTest</title>
            <failure>
                <message>Test ignored (without reason)!</message>
                <stack-trace>There are no stack trace</stack-trace>
            </failure>
            <steps>
                <step start="1412949558831" stop="1412949558832" status="pending">
                    <name>Future step</name>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="JUnit"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
